# Arquivo de Configuração para o Projeto Sentinela Verde
# ----------------------------------------------------
# Edite os valores abaixo para configurar a aplicação.

# Configurações do Broker MQTT
mqtt:
  broker_address: "test.mosquitto.org"
  port: 1883
  topic: "sentinela/dados_csv"

# Configurações da API de Qualidade do Ar (WAQI)
api:
  # Obtenha uma chave gratuita em: https://aqicn.org/data-platform/token/
  token: "845535b9a4be3918e97e326f4c550afad64b21d5" 
  city: "rio claro"
  # Intervalo em segundos para buscar novos dados da API (900s = 15 minutos)
  interval_seconds: 900

# Configurações de arquivos e logs
files:
  unified_csv: "dados_historicos_unificados.csv"
  log_file: "sentinela_verde.log"

# Parâmetros para os modelos de Machine Learning
models:
  decision_tree:
    feature_columns: 
      - 'Concentracao_Geral_PPM'
      - 'PM2.5_ug_m3'
      - 'PM10_ug_m3'
      - 'Temperatura_C'
      - 'Umidade_Relativa_percent'
    target_column: 'Qualidade_Ar_Calculada'
  
  forecasting:
    target_columns:
      - 'Concentracao_Geral_PPM'
      - 'PM2.5_ug_m3'
      - 'PM10_ug_m3'
    prediction_horizon_hours: 24

# Limites para classificação da qualidade do ar (usado para criar o alvo do modelo)
air_quality_limits:
  Concentracao_Geral_PPM: 300.0
  PM2.5_ug_m3: 25.0
  PM10_ug_m3: 50.0

